### ISSUE TITLE
Cocoapod Error for Swift 3.0

### ISSUE THREAD

**Issue by kutran** [i-schuetz/SwiftCharts#190]
In the instructions, I have put:

`pod 'SwiftCharts', '~> 0.5'`

Results in an following error:

```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `SwiftCharts (~> 0.5)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `SwiftCharts (~> 0.5)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

Am I doing anything wrong here?

**Comment by hpehpe** [comment]
I got that error too.

using:
source 'https://github.com/i-schuetz/SwiftCharts.git'

platform :osx, '10.9'

target 'Garning' do
  use_frameworks!
  pod 'SwiftCharts', '~> 0.5'
end

mitigated the problem but now I get:
Analyzing dependencies
[!] An unexpected version directory `Axis` was encountered for the `/Users/petereriksson/.cocoapods/repos/i-schuetz/SwiftCharts` Pod in the `SwiftCharts` repository.

**Comment by i-schuetz** [comment]
It seems something went wrong when I uploaded the pod last time. Should be fixed now, let me know if it works!

**Comment by hpehpe** [comment]
Thanks for the update, still get:
$ pod install
Analyzing dependencies
[!] An unexpected version directory `Axis` was encountered for the `/Users/petereriksson/.cocoapods/repos/i-schuetz/SwiftCharts` Pod in the `SwiftCharts` repository.

**Comment by i-schuetz** [comment]
Could you remove the "source" line from your podfile?

Also not sure about purpose of `platform :osx`. This library is only for iOS.

**Comment by hpehpe** [comment]
Ah, too bad. Is there a specific reason it wouldn't work for osx? I'd like to use it for a desktop app. I guess I have to have a look at adding the features needed for that myself...

Thanks

**Comment by i-schuetz** [comment]
There's no reason except I have no time to do this, if you want to, you can create a pull request. Happy to include this and continue maintaining it from now on. Some other people also have asked for it.

The main task would be to use generic versions for platform specific things like `UIView`, etc.

**Comment by i-schuetz** [comment]
P.S. the "please let me know" has a reason - there's a fork with a more advanced version of SwiftCharts which will be merged soon in this repo, so if you were to do this it would be better directly in this fork (or I try to merge it quicker).

**Comment by hpehpe** [comment]
I will either do it or commission someone to do so, but it will not be in the next month, so I guess you have time. I will make sure to let you know.

**Comment by kutran** [comment]
Works for me.

**Comment by johndpope** [comment]
This maybe a trick shot to get it working on osx - just replace uikit to uxkit.
I suspect it maybe released this year at WWDC.
It's apple's internal uikit for osx.  https://github.com/rpplusplus/UXKit
